steps:

  ###############
  ### Deploy code

  - name: hashicorp/terraform
    id: Terraform version
    args:
      - '-v'
    dir: infra

  - name: hashicorp/terraform
    id: Terraform init
    args:
      - 'init'
      - '-backend-config=bucket=${PROJECT_ID}-state'
    dir: infra
  
  #- name: hashicorp/terraform
  #  id: Terraform plan
  #  args:
  #    - 'plan'
  #    - '-var-file=tfvars/${PROJECT_ID}.tfvars'
  #    - '-out=/workspace/tfplan'
  #  dir: infra
  
  #- name: hashicorp/terraform
  #  id: Terraform apply
  #  args:
  #    - 'apply'
  #    - '-auto-approve'
  #    - '/workspace/tfplan'
  #  dir: infra


  ###############
  ### Testing etc

# Environment variables
options:
  env:
    - GOOGLE_PROJECT=${PROJECT_ID}
    - GOOGLE_REGION=${_REGION}